name: personal-finance-tracker

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, unlabeled, closed]

jobs:
  linting_and_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn install

      - name: Run Linting
        run: |
          yarn lint

      - name: Run Unit Tests
        run: |
          yarn test: unit

  build:
    needs: linting_and_unit_tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build Project
        run: |
          yarn build
